---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-install.yaml
  - https://raw.githubusercontent.com/skupperproject/skupper/1.3.0/cmd/site-controller/deploy-watch-current-ns.yaml
