apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: onlineboutique-appset
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: online-boutique-clusters
        requeueAfterSeconds: 10
  template:
    metadata:
      name: 'online-boutique-{{name}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/ansonmez/distributed-cloud-native-application'
        targetRevision: main
        path: 'online-boutique'
        helm: 
          valueFiles:
            - '{{name}}-values.yaml'
      destination:
        server: '{{server}}'
        namespace: onlineboutique
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
